---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: php7-deployment
  namespace: {{ .Values.service.namespace }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Values.service.php7 }}
        namespace: {{ .Values.service.namespace }}
      annotations:
{{ toYaml .Values.podAnnotations | indent 8 }}
    spec:
      containers:
      - name: {{ .Values.service.php7 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 9000
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: {{ .Values.service.namespace }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Values.service.nginx }}
        namespace: {{ .Values.service.namespace }}
      annotations:
{{ toYaml .Values.podAnnotations | indent 8 }}
    spec:
      containers:
      - name: {{ .Values.service.nginx }}
        image: "{{ .Values.nginx.repository }}:{{ .Values.nginx.tag }}"
        ports:
        - containerPort: 80