---
apiVersion: v1
kind: Service
metadata:  
  name: nginx-service
  namespace: {{ .Values.service.namespace }}
  labels:
    app: nginx-service
  annotations:
{{- if .Values.service.annotations }}
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
spec:
  selector:    
    app: nginx
    namespace: {{ .Values.service.namespace }}
  ports:  
  - name: http
    port: 80
---
apiVersion: v1
kind: Service
metadata:  
  name: php7-service
  namespace: {{ .Values.service.namespace }}
  labels:
    app: php7-service
  annotations:
{{- if .Values.service.annotations }}
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
spec:
  selector:    
    app: php7
    namespace: {{ .Values.service.namespace }}
  ports:  
  - name: http
    port: 9000