---
apiVersion: v1
kind: Service
metadata:  
  name: {{ .Values.service.nginx }}-service
  namespace: {{ .Values.service.namespace }}
  labels:
    app: {{ .Values.service.nginx }}-service
  annotations:
{{- if .Values.service.annotations }}
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
spec:
  selector:    
    app: {{ .Values.service.nginx }}
    namespace: {{ .Values.service.namespace }}
  ports:  
  - name: http
    port: 80
---
apiVersion: v1
kind: Service
metadata:  
  name: {{ .Values.service.php7 }}-service
  namespace: {{ .Values.service.namespace }}
  labels:
    app: {{ .Values.service.php7 }}-service
  annotations:
{{- if .Values.service.annotations }}
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
spec:
  selector:    
    app: {{ .Values.service.php7 }}
    namespace: {{ .Values.service.namespace }}
  ports:  
  - name: tcp
    port: 9000
    protocol: TCP