---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: debian-ext
spec:
  hosts:
  - deb.debian.org
  - ftp.us.debian.org
  - security.debian.org
  ports:
  - number: 80
    name: http
    protocol: HTTP
  resolution: DNS
  location: MESH_EXTERNAL