---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: {{ .Values.service.namespace }}
  labels:
    app: nginx
    namespace: {{ .Values.service.namespace }}
  annotations:
{{- if .Values.service.annotations }}
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 80
    - name: https
      port: {{ .Values.service.httpsPort }}
      targetPort: 80
  selector:
    app: nginx
    namespace: {{ .Values.service.namespace }}
    
---
apiVersion: v1
kind: Service
metadata:  
  name: php7-service
  namespace: {{ .Values.service.namespace }}
spec:
  selector:    
    app: php7
    namespace: {{ .Values.service.namespace }}
  type: ClusterIP
  ports:  
  - name: http
    port: 9000
    targetPort: 9000
    protocol: TCP