---
apiVersion: v1
kind: Service
metadata:  
  name: php7-service
  namespace: {{ .Values.service.namespace }}
spec:
  selector:    
    app: php7
    namespace: {{ .Values.service.namespace }}
  type: ClusterIP
  ports:  
  - name: http
    port: 9000
    targetPort: 9000
    protocol: TCP