---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: nginx-service
spec:
  hosts:
  - "*"
  gateways:
  - {{ .Values.virtualservice.gateway }}
  http:
  - match:
    - uri:
        prefix: {{ .Values.virtualservice.prefix1 }}
    - uri:
        prefix: {{ .Values.virtualservice.prefix2 }}
    route:
    - destination:
        port:
          number: 80
        host: {{ .Values.virtualservice.host }}