---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.virtualservice.name }}
  namespace: {{ .Values.service.namespace }}
  labels:
    app: nginx
    namespace: {{ .Values.service.namespace }}
spec:
  hosts:
  - "*"
  gateways:
  - {{ .Values.virtualservice.gateway }}
  http:
  - match:
    - uri:
        exact: {{ .Values.virtualservice.prefix1 }}
    - uri:
        prefix: {{ .Values.virtualservice.prefix2 }}
    route:
    - destination:
        port:
          number: 80
        host: {{ .Values.virtualservice.host }}