# Default values for kiam.

replicaCount: 1
service: 
  namespace: wordpress
  type: LoadBalancer
  port: 80
  httpsPort: 443
virtualservice:
  name: nginx-service-1
  gateway: nginx-gateway-1
  prefix1: /status1
  prefix2: /delay1
  host: nginx-service  
image:
  repository: kewlvishnu/phpfpm-app
  tag: 0.3.0
  pullPolicy: IfNotPresent

nginx:
  repository: kewlvishnu/nginx
  tag: 0.1.0
  pullPolicy: IfNotPresent

podAnnotations: {}